### ISSUE TITLE
Completeness & Cardinality

### ISSUE THREAD

**Issue by CharlieBatchelor** [DUNE-DAQ/trigger#167]
During the June 2022 and November 2022 cold box APA tests at CERN, EHN1, the trigger subsystem of DUNE DAQ was observed to crash occasionally at `stop` time. The root cause of this appears to be that `completeness` is not being achieved in the [zipper](https://github.com/DUNE-DAQ/trigger/blob/58900fc1eb1dc681cc2cd1d60a3b647b7e82a76a/plugins/zipper.hpp) code. 

### Completeness & Cardinality
`completeness` is a measure of how many input queues we see occupied with `TPSets` during run time.  `cardinality` is a configurable parameter for trigger that should be set to the number of input queues that we _expect_ to see, occupied with `TPSets`. `completeness` is achieved when `completeness >= cardinality` is true.

### Stop Time Issue
If completeness _is not_ achieved, then _all_ `TPSets` are stored in the buffer until `stop` time when the `flush()` function is called. At this point, all the `TPSets` are forced through the system at once, resulting in many `FollyQueue` error messages of the type:

`ERROR iomanager/include/iomanager/Sender.hpp:96] zip_1.output_to_tam_1.input: Unable to push within timeout period (timeout period was 10 milliseconds)`

### Re-Thinking Cardinality Logic?
During SW TPG runs, the number of input `TPSet`  queues is generally set to the number of active WIB links.  A feature of the FW TP runs that 2 queues can be initiated where only 4 WIB links are being used, which is enough to send `TPSets` on only 1/2 queues. This prevents `completeness` from being achieved and reproduces the above described stopping problem, with the current state of the `zipper` code. Going forwards, we should probably re-think this `cardinality` / `completeness` logic to handle empty queues when they are expected during test runs.

**Comment by CharlieBatchelor** [comment]
### Temporary Fix

I've taken some FW TPG runs with a temporary fix in branch [cbatchelor/temporary_cardinality_fix](https://github.com/DUNE-DAQ/trigger/tree/cbatchelor/temporary_cardinality_fix). This is certainly not a long term solution, but has been used to take successfully stopping runs with FW TPG runs on 7 links where 2 queues are active. It may be used in the ongoing APA runs at CERN, EHN1 to avoid having to manually change the `cardinality` parameter.


### A Proposal
One proposal I discussed briefly with Kunal is to soften the stringent requirement of `completeness` by reducing the required fraction of `TPSet` occupied links from 100% to perhaps 60-70% for SW TPG runs, and perhaps 50% for FW TPG runs. This seems a little more appropriate to me as we move forward from testing on single to multiple APAs concurrently, where the likelihood of seeing no `TPSets` on some subset of the `n` input queues is perhaps increased. The precise acceptable fraction of active input queues should be discussed.

**Comment by brettviren** [comment]
Just to be sure, the zipper is being configured with a "0" max latency in these tests, right?  This means it operates in lossless but unbound latency mode.

I think the right thing to do may be simply set this to a reasonable non-zero value to guarantee a finite maximum latency.  Loss of any subsequent tardy messages is then a "good riddance" situation.  Reasonable, in my mind is something well above your favorite number of sigma of natural input rate fluctuations and well below the 10s depth of the FE buffers.  My guess somewhere around 100ms is right.

On top of that, your idea of a "stream watchdog" to dynamically determine the health of each stream and to adjust the zipper's cardinality accordingly would also add value.

When in latency guarantee mode and with a dead input stream, the zipper will always be introducing latency near the configured max.  It must constantly wait that maximum time for messages that will never come from the dead stream.

So, adding a stream watchdog to reduce the cardinality on top of the latency guarantee mode will mean that the zipper can go back to normal waiting.  That is, the watchdog helps keep the mean latency introduced by the zipper to be that of the input rates instead of the configured max.

**Comment by CharlieBatchelor** [comment]
So the runs that produced this error _were not_ using a zipper configured in the lossless case (with `max_latency_ms = 0`) but in fact with `max_latency_ms = 100`. As we discussed on Slack, there are two separate issues where the "tardy" input `TPSet` messages arise, and they are:

1. When `completeness` is not achieved at all during the run, and all `TPSets` get buffered until `stop` time when the `flush()` is called. _All_ `TPSets` are pushed through the system at once, which results in many error messages like  "`Unable to push within timeout period (timeout period was 10 milliseconds)`", as we might expect.

2. The second issue is genuinely late `TPSets`, which are when the `zipper` is behaving as we want it to. These messages are produced during run time, and @MRiganSUSX and I have tested the latency configurable by adjust from `max_latency_ms = 100` (which is the default) to `max_latency_ms = 200`, which has shown to remove all tardy input messages. I think this is the behaviour you're describing above?

It's true that (1) is still to be fully understood, since we expect a non-zero finite max latency to just send out `TPSets` even if it hasn't seen `TPSets` from all configured input queues. I think this is also what you're saying above?

**Comment by CharlieBatchelor** [comment]
### Medium Term Cardinality Fix

I've created a branch of `trigger` and `daqconf` from `patch/v3.2.x` which have introduced two new parameters. The aim here is to configure the zipper (specifically the `TPZipper`) to tolerate incompleteness in the following way:

1.  `tolerate_incompleteness: false` - False by default, but set to `true` and the zipper `bool complete` function will consider passing a pseudo-complete state, i.e. return `true` when not all `cardinality` links are observed to be active.
2. `completeness_tolerance: 1` - Set to 1 by default. It's the maximum number of inactive links we are willing to observe and still pass `TPSets` before refusing to pass a pseudo-complete state.

These branches have been tested on a FW TPG run on APA 2 as of this morning, where we managed to start with 2 active queues, and break one of them mid-run. Trigger was able to cope with this whilst emitting several timeout on request warnings as should be expected, before recovering and continuing to emit HSI triggers without error. A clean `stop_run` was also observed.

**Comment by brettviren** [comment]
FYI, I will look into problem 1 (finite latency + missing source = no messages) at the core zipper algorithm level.  It may take a few days to first get some other things to a resting point.

**Comment by brettviren** [comment]
@CharlieBatchelor I think this is now fixed in my upstream.  Take a look at the linked issue in the zipper repo for some details.  You can check `test_absent.cpp` if you want to see a test that reproduced the problem and now passes.

I tagged this fix https://github.com/brettviren/zipper/releases/tag/1.0.1 

Version 1.0.0 is also tagged with the version more or less what is still in DUNE-DAQ/trigger right now.

There are some clang-tidy-induced changes between `zipper/zipper.hpp` and the copy in this repo.  I'm not sure how best to refresh the copy here.  Maybe just copy and some clang-tidy script will auto fix?  

I wonder if you'd like to do that re-vendoring?

Thanks again for your efforts to find this problem!

**Comment by CharlieBatchelor** [comment]
Hi @brettviren - I'm getting some compilation errors when exchanging the current `zipper.hpp` for the one in [here](https://github.com/brettviren/zipper/commit/23daded7e883ef93fc58c962713075b30aa2f10b#diff-a99305a5414084207d9ba313db9f90b2351ae19acfaa722985ab630ea06f2a58). I'm building off develop, from the latest nightly. I'll try to have a look at these today.

**Comment by brettviren** [comment]
Hi @CharlieBatchelor and thanks.

Maybe if you say the error message I can suggest something.  

I no longer have a working DAQ dev env but will remake one and do the merge if you get stuck.

**Comment by CharlieBatchelor** [comment]
@brettviren - It was a quick fix! `target_cardinality` just had to be declared as a `size_t` instead of `int`. I've created  #180 to get the fix ready for the upcoming `v3.2.x` VDCB runs for now. Thanks for this.

**Comment by brettviren** [comment]
Ah, excellent.  Thanks!

**Comment by MRiganSUSX** [comment]
Closed after review at the trigger workshop.
