### ISSUE TITLE
Trigger: Performance tests

### ISSUE THREAD

**Issue by MRiganSUSX** [DUNE-DAQ/trigger#206]
Ideas for trigger performance measuring and monitoring:

- Write an application to track CPU usage and RAM usage per trigger module and makes plot of that. This is to attempt a performance test without touching the trigger DUNE-DAQ while doing so.
- Run the above application on a single APA with one link and one Maker and CRT. Then see how it scales (multiple links, multiple makers, multiple APAs)
- Is the latency affected by the trigger rate?
- Latency plots on Grafana: How long it takes for a TC to propagate through the system, calculated this way: TC received vs TC sent
- Latency plots on Grafana: Comparing data times to wall-clock time
- Standardise all latency measurements for all trigger modules from start to finish (buffer, zipper...), Grafana compatible

**Comment by ArturSztuc** [comment]
I think this can be probably closed.

We now have:
1. trgtools, where we can measure algorithm's cpu performance by measuring how long it takes per TP
2. Online latency measurements, that have now helped us to uncover issues on multiple occasions, in both v4 and v5 systems.

I would say far more could be done, but probably as a package for the entire DAQ rather than trigger-specific -- trigger-specific performance measurements are now there, usable and useful.
